In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.random.rand(5)

array([0.18555147, 0.18552618, 0.70449313, 0.95354987, 0.47054769])

In [19]:
np.random.randn(2)

array([-0.07057014,  1.84221079])

In [21]:
np.random.randint(1,100,10)

array([40, 43, 73, 24, 52, 51, 25, 89, 80,  5])

In [22]:
arr = np.arange(25)

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [24]:
ranarr = np.random.randint(0,50,10)

In [25]:
ranarr

array([18, 19, 11, 46, 18, 14, 17, 17, 35, 29])

In [26]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [27]:
ranarr.max()

46

In [28]:
ranarr.min()

11

#Numpy Indexing and Selection

In [29]:
import numpy as np

In [32]:
arr = np.arange(0,11)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
arr[1:5]

array([1, 2, 3, 4])

In [37]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [38]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [39]:
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [40]:
slice_of_arr = arr[0:6]

In [41]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

#Slicing for 2-D Arrays


In [42]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [43]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [44]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [45]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [46]:
arr[arr<5]

array([0, 1, 2, 3, 4])

In [47]:
arr_2d = np.arange(50).reshape(5,10)

In [48]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [49]:
arr_2d[1:4,1:4]

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

#Numpy Operations


In [50]:
import numpy as np

In [51]:
arr = np.arange(0,11)

In [52]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [53]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [54]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [55]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [56]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])